# Generated by Django 4.2.2 on 2023-06-11 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0003_achredeem_transfer_mopredeem_redeem_list"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mopredeem",
            name="redeem_list",
            field=models.ManyToManyField(blank=True, to="data.mopredeem"),
        ),
    ]
