# Generated by Django 4.2.2 on 2023-06-12 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0004_alter_mopredeem_redeem_list"),
    ]

    operations = [
        migrations.AddField(
            model_name="achredeem",
            name="on_file",
            field=models.CharField(
                choices=[("OF", "On File"), ("N", "New")], default=1, max_length=10
            ),
            preserve_default=False,
        ),
    ]
