# Generated by Django 4.2.2 on 2023-06-13 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0005_achredeem_on_file"),
    ]

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name="catogorie",
            name="unique by name",
        ),
        migrations.AddConstraint(
            model_name="catogorie",
            constraint=models.UniqueConstraint(fields=("name",), name="cateogorie"),
        ),
        migrations.AddConstraint(
            model_name="paymentmethod",
            constraint=models.UniqueConstraint(fields=("name",), name="payment method"),
        ),
        migrations.AddConstraint(
            model_name="game",
            constraint=models.UniqueConstraint(fields=("name",), name="game"),
        ),
        migrations.AlterField(
            model_name="transfer",
            name="from_game",
            field=models.ForeignKey(
                max_length=255,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="_from_game",
                to="data.game",
                verbose_name="From Game",
            ),
        ),
        migrations.AlterField(
            model_name="transfer",
            name="to_game",
            field=models.ForeignKey(
                max_length=255,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="_to_game",
                to="data.game",
                verbose_name="To Game",
            ),
        ),
    ]
