# Generated by Django 4.2.2 on 2023-06-15 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0007_remove_mopredeem_category_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="achredeem",
            options={"verbose_name_plural": "ACH REDEEM"},
        ),
        migrations.AlterModelOptions(
            name="catogorie",
            options={"verbose_name_plural": "CATEGORIES"},
        ),
        migrations.AlterModelOptions(
            name="game",
            options={"verbose_name_plural": "GAMES"},
        ),
        migrations.AlterModelOptions(
            name="mopredeem",
            options={"verbose_name_plural": "MOP REDEEM"},
        ),
        migrations.AlterModelOptions(
            name="paymentmethod",
            options={"verbose_name_plural": "PAYMENT METHODS"},
        ),
        migrations.AlterModelOptions(
            name="redeemlist",
            options={"verbose_name_plural": "REDEEM LISTS"},
        ),
        migrations.AlterModelOptions(
            name="transfer",
            options={"verbose_name_plural": "TRANSFERS"},
        ),
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name_plural": "USERS"},
        ),
        migrations.RemoveField(
            model_name="catogorie",
            name="id",
        ),
        migrations.RemoveField(
            model_name="paymentmethod",
            name="id",
        ),
        migrations.AlterField(
            model_name="catogorie",
            name="name",
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="paymentmethod",
            name="name",
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="redeemlist",
            name="refund",
            field=models.FloatField(blank=True, null=True, verbose_name="Refund"),
        ),
        migrations.AlterField(
            model_name="redeemlist",
            name="send",
            field=models.FloatField(blank=True, null=True, verbose_name="Send"),
        ),
    ]

