# Generated by Django 4.2.2 on 2023-07-03 08:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0008_alter_achredeem_options_alter_catogorie_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                (
                    "system_in",
                    models.FloatField(
                        blank=True, default=0.0, null=True, verbose_name="System In"
                    ),
                ),
                (
                    "system_out",
                    models.FloatField(
                        blank=True, default=0.0, null=True, verbose_name="System Out"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "DAILY REPORT",
            },
        ),
        migrations.AddField(
            model_name="achredeem",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="redeemlist",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="transfer",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="RedeemGameList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "amount",
                    models.FloatField(
                        blank=True, default=0.0, null=True, verbose_name="Amount"
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        max_length=255,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="_game",
                        to="data.game",
                        verbose_name="Game",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "REDEEM LIST",
            },
        ),
    ]
