# Generated by Django 4.2.2 on 2023-07-03 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0009_dailyreport_achredeem_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="redeemgamelist",
            name="customer",
            field=models.CharField(
                default="aanish", max_length=255, verbose_name="Customer Name"
            ),
            preserve_default=False,
        ),
    ]
