# Generated by Django 4.2.2 on 2023-07-04 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0011_remove_dailyreport_system_in_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transfer",
            name="daily_report",
        ),
        migrations.AddField(
            model_name="game",
            name="daily_report",
            field=models.ForeignKey(
                blank=True,
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="data.dailyreport",
            ),
            preserve_default=False,
        ),
    ]
