# Generated by Django 4.2.2 on 2023-07-10 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0013_alter_game_daily_report"),
    ]

    operations = [
        migrations.CreateModel(
            name="GameSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "system_in",
                    models.FloatField(
                        blank=True, default=0.0, null=True, verbose_name="In"
                    ),
                ),
                (
                    "system_out",
                    models.FloatField(
                        blank=True, default=0.0, null=True, verbose_name="Out"
                    ),
                ),
                (
                    "transfer",
                    models.FloatField(
                        blank=True, default=0.0, null=True, verbose_name="Transfer"
                    ),
                ),
                (
                    "cashout",
                    models.FloatField(
                        blank=True, default=0.0, null=True, verbose_name="Cashout"
                    ),
                ),
                (
                    "daily_report",
                    models.ForeignKey(
                        max_length=255,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="_daily_report",
                        to="data.dailyreport",
                        verbose_name="DailyReport",
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        max_length=255,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="_gamesummary",
                        to="data.game",
                        verbose_name="Game",
                    ),
                ),
            ],
        ),
    ]
